---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{R}
rawDAct <- read.csv("activity.csv")

DAct <- na.omit(rawDAct) ### remove na data
```

## What is mean total number of steps taken per day?
```{r}
StepsDayMean <-aggregate(DAct$steps, 
                list(day = DAct$date),
                mean)
```


####Output Mean
```{r}

print(StepsDayMean)
```



## What is median total number of steps taken per day?
```{r}
StepsDayMedian <-aggregate(DAct$steps, 
                list(day = DAct$date),
                FUN = median)
```



                
####Output Median
```{r}
print(StepsDayMedian)

```




### Plot histogram of steps-day

```{r}
StepsDaySum <-aggregate(DAct$steps, 
                list(day = DAct$date),
                sum)

hist(StepsDaySum$x, main = "Historgram of Steps per day")


```


## What is the average daily activity pattern?
```{r}

plot(StepsDayMean$day,StepsDayMean$x, type = "l",  main = "Average Daily Activity Pattern")

```


####Max Steps

```{r}
MaxStepsIn5Min <- max(DAct$steps)

MaxStepInterval<- DAct$interval[DAct$steps==MaxStepsIn5Min]
DayOfMaxStepInterval <- round(615/12/24)

print(MaxStepsIn5Min)


```



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
